[package]
name = "recall_fendermint_actor_blobs_shared"
description = "Shared resources for blobs"
license.workspace = true
edition.workspace = true
authors.workspace = true
version.workspace = true

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = { workspace = true }
data-encoding = { workspace = true }
recall_fil_actors_runtime = { workspace = true }
recall_frc42_dispatch = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_shared = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, features = ["derive"] }

recall_actor_sdk = { workspace = true }
recall_ipld = { workspace = true }

[features]
fil-actor = ["recall_fil_actors_runtime/fil-actor"]
