---
# TODO: Remove Github secrets section once this repo is public
- name: Include GitHub secrets
  include_vars:
    file: github_secrets.yml

- name: Download and extract IPC repository
  shell: |
    set -e
    TARGET_DIR="/home/{{ ansible_user_id }}/ipc"
    mkdir -p $TARGET_DIR
    curl -H "Authorization: token {{ github_token }}" -L https://api.github.com/repos/amazingdatamachine/ipc/zipball/main -o /tmp/ipc.zip
    unzip -o /tmp/ipc.zip -d $TARGET_DIR
    mv $TARGET_DIR/*/* $TARGET_DIR/
    rmdir $TARGET_DIR/*/
    rm /tmp/ipc.zip
    cd $TARGET_DIR
    npm install
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"  # Ensure npm is in the PATH

- name: Install NPM dependencies
  npm:
    path: /home/{{ ansible_user_id }}/ipc
    state: present

- name: Build Rust components
  shell: |
    source $HOME/.cargo/env
    cd /home/{{ ansible_user_id }}/ipc
    cargo build --release
  args:
    executable: /bin/bash

- name: Configure IPC node
  copy:
    src: /path/to/local/config.yaml
    dest: /home/{{ ansible_user_id }}/ipc/config.yaml

- name: Start IPC node
  shell: |
    cd /home/{{ ansible_user_id }}/ipc
    npm start
  args:
    chdir: /home/{{ ansible_user_id }}/ipc

