[package]
name = "recall_fendermint_vm_encoding"
description = "Utilities for encoding some of the primitive FVM types with serde"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
serde_with = { workspace = true }
num-traits = { workspace = true }

cid = { workspace = true }
fvm_shared = { workspace = true }
recall_ipc_api = { workspace = true }
