[package]
name = "fendermint_vm_iroh_resolver"
description = "Resolve iroh content in messages"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-stm = { workspace = true }
hex = { workspace = true }
im = { workspace = true }
iroh = { workspace = true }
libp2p = { workspace = true }
prometheus = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }

recall_ipc_api = { workspace = true }
ipc_ipld_resolver = { workspace = true }
ipc-observability = { workspace = true }

fendermint_vm_topdown = { path = "../topdown" }

[dev-dependencies]
rand = { workspace = true }
tokio = { workspace = true }
