[package]
name = "recall_fendermint_vm_genesis"
description = "Genesis data used to initialize the FVM state when the chain is created"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
cid = { workspace = true, optional = true }
fvm_shared = { workspace = true }
recall_ipc_api = { workspace = true }
multihash = { workspace = true, optional = true }
num-traits = { workspace = true }
quickcheck = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true }
serde_with = { workspace = true }
tendermint = { workspace = true }

recall_fendermint_actor_eam = { workspace = true }
recall_fendermint_crypto = { workspace = true }
recall_fendermint_testing = { workspace = true, features = ["golden"] }
recall_fendermint_vm_core = { workspace = true }
recall_fendermint_vm_encoding = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
fvm_ipld_encoding = { workspace = true }
multihash = { workspace = true }
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
serde_json = { workspace = true }
recall_ipc_types = {workspace = true}

# Enable arb on self for tests.
recall_fendermint_vm_genesis = { path = ".", features = ["arb"] }

[features]
default = []
arb = [
    "arbitrary",
    "quickcheck",
    "fvm_shared/arb",
    "recall_fendermint_testing/arb",
    "rand",
    "cid",
    "multihash",
]
