---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install system dependencies
  apt:
    name:
      - build-essential
      - bzr
      - ca-certificates
      - clang
      - cmake
      - curl
      - gcc
      - git
      - gnupg
      - hwloc
      - jq
      - libhwloc-dev
      - libssl-dev
      - mesa-opencl-icd
      - ocl-icd-opencl-dev
      - pkg-config
      - protobuf-compiler
      - wget
    state: present
    update_cache: yes

- name: Install Rust
  shell: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    source $HOME/.cargo/env
  args:
    executable: /bin/bash

- name: Install Foundry
  shell: |
    curl -L https://foundry.paradigm.xyz | bash
    source ~/.bashrc
    foundryup
    echo 'export PATH=$PATH:$HOME/.foundry/bin' >> $HOME/.bashrc
    source ~/.bashrc
  args:
    executable: /bin/bash
    creates: ~/.foundry/bin/forge
  register: foundry_install

- name: Update Ansible environment PATH
  set_fact:
    ansible_env: "{{ ansible_env | combine({'PATH': ansible_env.PATH ~ ':' ~ ansible_env.HOME ~ '/.foundry/bin'}) }}"
  when: foundry_install.changed
