---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install system dependencies
  apt:
    name:
      - build-essential
      - bzr
      - ca-certificates
      - clang
      - cmake
      - curl
      - gcc
      - git
      - gnupg
      - hwloc
      - jq
      - libhwloc-dev
      - libssl-dev
      - mesa-opencl-icd
      - ocl-icd-opencl-dev
      - pkg-config
      - protobuf-compiler
      - wget
    state: present
    update_cache: yes

- name: Install Rust
  shell: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    source $HOME/.cargo/env
  args:
    executable: /bin/bash

- name: Install Foundry
  shell: |
    curl -L https://foundry.paradigm.xyz | bash
    ~/.foundry/bin/foundryup
  args:
    executable: /bin/bash
    creates: "~/.foundry/bin/forge"
  register: foundry_install

- name: Get Foundry bin path
  shell: echo ~/.foundry/bin
  register: foundry_bin_path_result
  changed_when: false

- name: Set fact for Foundry bin path
  set_fact:
    FOUNDRY_BIN_PATH: "{{ foundry_bin_path_result.stdout }}"
