[package]
name = "fendermint_actor_blobs_testing"
description = "Test utils for blobs"
license.workspace = true
edition.workspace = true
authors.workspace = true
version.workspace = true

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
rand = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
iroh-base = { workspace = true, features = ["key"] }
fvm_shared = { workspace = true }

recall_fendermint_actor_blobs_shared = { path = "../shared" }