[package]
name = "fendermint_actor_rebate_pool_shared"
description = "Shared resources for rebate_pool"
license.workspace = true
edition.workspace = true
authors.workspace = true
version = "0.1.0"

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
fvm_shared = { workspace = true }
fvm_ipld_encoding = { workspace = true }
num-derive = { workspace = true }
serde_tuple = { workspace = true }
serde = { workspace = true, features = ["derive"] }
num-traits = { workspace = true }
frc42_dispatch = { workspace = true }
