[package]
name = "fendermint_vm_interpreter"
description = "Execute messages using the FVM"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
async-stm = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
cid = { workspace = true }
ethers = { workspace = true }
recall_fil_actor_adm = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
fvm = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_car = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_shared = { workspace = true }
hex = { workspace = true }
recall_ipc_api = { workspace = true }
recall_ipc_actors_abis = { workspace = true }
ipc-observability = { workspace = true }
iroh = { workspace = true }
iroh-base = { workspace = true }
libipld = { workspace = true }
num-traits = { workspace = true }
pin-project = { workspace = true }
prometheus = { workspace = true }
quickcheck = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
snap = { workspace = true }
strum = { workspace = true }
tendermint = { workspace = true }
tendermint-rpc = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

recall_fendermint_actors_api = { workspace = true }
recall_fendermint_actor_activity_tracker = { workspace = true }
recall_fendermint_actor_blobs = { workspace = true }
recall_fendermint_actor_blob_reader = { workspace = true }
recall_fendermint_actor_blobs_shared = { workspace = true }
recall_fendermint_actor_bucket = { workspace = true }
recall_fendermint_actor_chainmetadata = { path = "../../actors/chainmetadata" }
recall_fendermint_actor_eam = { workspace = true }
recall_fendermint_actor_gas_market_eip1559 = { path = "../../actors/gas_market/eip1559" }
recall_fendermint_actor_recall_config = { workspace = true }
recall_fendermint_actor_recall_config_shared = { workspace = true }
recall_fendermint_actor_timehub = { workspace = true }
recall_fendermint_actors = { path = "../../actors" }
recall_fendermint_crypto = { workspace = true }
fendermint_eth_hardhat = { path = "../../eth/hardhat" }
recall_fendermint_rpc = { workspace = true }
recall_fendermint_testing = { workspace = true, optional = true }
fendermint_tracing = { path = "../../tracing" }
recall_fendermint_vm_actor_interface = { path = "../actor_interface" }
recall_fendermint_vm_core = { path = "../core" }
recall_fendermint_vm_encoding = { path = "../encoding" }
fendermint_vm_event = { path = "../event" }
recall_fendermint_vm_genesis = { path = "../genesis" }
fendermint_vm_iroh_resolver = { path = "../iroh_resolver" }
recall_fendermint_vm_message = { workspace = true }
fendermint_vm_resolver = { path = "../resolver" }
fendermint_vm_topdown = { path = "../topdown" }
recall_executor = { path = "../../../recall/executor" }
recall_kernel = { path = "../../../recall/kernel" }

recall_merkle_tree_rs = { workspace = true }

[dev-dependencies]
fvm = { workspace = true, features = ["arb", "testing"] }
hex = { workspace = true }
multihash = { workspace = true }
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
tempfile = { workspace = true }

recall_fendermint_testing = { path = "../../testing", features = ["golden"] }
recall_fendermint_vm_genesis = { path = "../genesis", features = ["arb"] }
fendermint_vm_interpreter = { path = ".", features = ["arb"] }
recall_fendermint_vm_message = { path = "../message", features = ["arb"] }

[features]
default = []
bundle = []
arb = [
    "arbitrary",
    "quickcheck",
    "fvm_shared/arb",
    "recall_fendermint_testing/arb",
    "rand",
]
test-util = []
