keystore_path = "~/.ipc"

# Anvil root
[[subnets]]
id = "/r31337"

[subnets.config]
network_type = "fevm"
provider_http = "http://127.0.0.1:8545"
auth_token = ""

[[subnets]]
# note: these values are updated during startup
id = "/r31337/t410fkzrz3mlkyufisiuae3scumllgalzuu3wxlxa2ly"

[subnets.config]
network_type = "fevm"
provider_http = "http://127.0.0.1:8645"
registry_addr = "0x74539671a1d2f1c8f200826baba665179f53a1b7"
gateway_addr = "0x77aa40b105843728088c0132e43fc44348881da8"
