replicaCount: 1

image:
  repository: amazingdatamachine/ipc-node-validator
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

resources:
  limits:
    cpu: "500m"
    memory: "128Mi"
  requests:
    cpu: "250m"
    memory: "64Mi"

serviceAccount:
  create: true
  name: ""

podSecurityContext: {}
securityContext: {}

config:
  config.yaml: |
    # IPC Node Validator configuration
    [validator]
    # Your configuration details here

