[package]
name = "recall_fendermint_vm_message"
description = "Messages (transactions) received on chain and passed on to the FVM"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
blake2b_simd = { workspace = true }
cid = { workspace = true }
ethers-core = { workspace = true }
iroh-base = { workspace = true, features = ["key"] }
lazy_static = { workspace = true }
num-traits = { workspace = true }
quickcheck = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true }
serde_tuple = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }

fvm_shared = { workspace = true, features = ["crypto"] }
fvm_ipld_encoding = { workspace = true }
recall_ipc_api = { workspace = true }

recall_fendermint_actor_blobs_shared = { workspace = true }
recall_fendermint_crypto = { workspace = true }
recall_fendermint_vm_encoding = { workspace = true }
recall_fendermint_vm_actor_interface = { workspace = true }
recall_fendermint_testing = { workspace = true, optional = true }

[dev-dependencies]
ethers = { workspace = true }
hex = { workspace = true }
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }

# Enable arb on self for tests.
# Ideally we could do this with `#[cfg(any(test, feature = "arb"))]`,
# however in that case all the extra dependencies would not kick in,
# and we'd have to repeat all those dependencies.
recall_fendermint_vm_message = { path = ".", features = ["arb"] }
# `recall_fendermint_testing` is used by `recall_fendermint_vm_message`,
# but only if the "arb" feature is enabled (which is only for tests). As
# mentioned above, this means we have to have `recall_fendermint_testing`
# as a dev-dep and dep, _and_ we have to have `recall_fendermint_vm_message`
# as a dev-dep of itself... TODO: this seems hacky
recall_fendermint_testing = { path = "../../testing", features = ["golden"] }

[features]
arb = [
    "arbitrary",
    "quickcheck",
    "fvm_shared/arb",
    "cid/arb",
    "rand",
    "recall_fendermint_testing/arb",
]
