[package]
name = "recall_kernel_ops"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
fvm = { workspace = true }
